language: ruby
dist: trusty
cache: bundler
rvm:
- 2.0
- 2.1
- 2.2
- 2.3
- 2.4
- jruby-19mode
- jruby-head
matrix:
  include:
  - rvm: rubinius-3
    env:
      - RUBYOPT="-rbundler/deprecate"
env:
  global:
    secure: iWhWlsjVg1ut2PSjBhDCwmRRNG5e3Q1TSRNQyTcVbuq8JNC12amObcp6+xlMur0fBtdgNgiE70iXlpC3WD+wRSRumXfSUwhzIk88XuFQtwm62lo3oboJp/LqiTJfexm5yuBC8tRkHfPsR0aW+7fplMElQWaMPl47Rt51KKJJKQE=
addons:
  apt:
    packages:
    - libdiscid0
sudo: true
before_install:
- gem install codeclimate-test-reporter
script: bundle exec rake test
after_script: '[ "${TRAVIS_RUBY_VERSION}" = "2.4" ] && codeclimate-test-reporter'
deploy:
  provider: rubygems
  api_key:
    secure: hM0SrqauBY3aOh9y6ri9R+DAjaArsH8V41IjUP9PYya5fV+K7JyNCzZB9KaolZGfnLc/U32hUDItKJaTw5GpaA8/wHj9cndkyjfPsjTaIzY8GODdBwDpquDt8yiHnMH6apRKn+habPheXQ1fQwJsD42HSUZIvH97pj20Nis2Ux4=
  gem: discid
  on:
    branch: master
    tags: true
    ruby: '2.4'
