language: ruby
dist: trusty
cache: bundler
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - jruby-19mode # JRuby in 1.9 mode
  - jruby
  # - rubinius-2
  - rubinius-3
addons:
  apt:
    packages:
    - libdiscid0
sudo: true
before_install:
  - gem install codeclimate-test-reporter
script:
  - bundle exec rake test
  - codeclimate-test-reporter
