language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.3
  - 2.3.0
  - 2.4.0
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-2
addons:
  apt:
    packages:
    - libdiscid0
sudo: false
script:
  - bundle exec rake test
  - CODECLIMATE_REPO_TOKEN=40f40f3d9e79b5e7051d7564172541932d6799ba585a5ada684695c0fb3e5e5e codeclimate-test-reporter
