language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-18mode
  - rbx-19mode
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libdiscid0
script: bundle exec rake test